# Site settings
title: The YnoGuy
description: 'Wine+Software by Bill Langley'
url: 'https://brainstormwilly.github.io/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Bill Langley'
  email: bill@ynoguy.com
  twitter_username: theynoguy
  facebook_username: Yno-Guy
  github_username:  BrainstormWilly
  linkedin_username:  BrainstormWilly

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
